### ISSUE TITLE
mepo allows a bad components.yaml

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#150]
I just tried a `components.yaml` that has:
```yaml
ESMA_cmake:
  local: ./ESMA_cmake
  remote: ../ESMA_cmake.git
  tag: v3.3.6
  branch: develop
  develop: develop
```
and it worked. I'd prefer that you can't have both `tag:` and `branch:` in the yaml file.
