### ISSUE TITLE
mepo clone with recurse-submodules

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#24]
Add ability for `mepo clone` to recurse.

And I guess, `diff`, `status`, ...

**Comment by tclune** [comment]
To be clear - this just means to use the --recursive of git itself.  Not to re-introduce the notion of nested mepo specifications.

**Comment by mathomp4** [comment]
@tclune Okay. I think I have a test set up such that you can do:
```
mepo clone --recurse-submodules
```
But my question is: is this what you want? Or, rather, should the recursive attribute be part of the YAML file, i.e.,:
```yaml
pfunit:
  local: ./@pfunit
  remote: git@github.com:Goddard-Fortran-Ecosystem/pFUnit.git
  tag: v4.1.5
  recurse: True
```
