### ISSUE TITLE
Mepo state files (.mepo/state.json) should include the full path to remote

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/mepo#312]
Currently the state file (`.mepo/state.json`) mirrors the registry, and looks like
```yaml
[
  {
    "name": "GEOSgcm",
    "local": ".",
    "remote": "../GEOSgcm.git",
    "version": [
      "v11.5.2",
      "t",
      true
    ],
    "sparse": null,
    "develop": "main",
    "recurse_submodules": null,
    "fixture": true,
    "ignore_submodules": null
  },
  {
    "name": "env",
    "local": "@env",
    "remote": "../ESMA_env.git",
    "version": [
      "v4.25.1",
      "t",
      true
    ],
    "sparse": null,
    "develop": "main",
    "recurse_submodules": null,
    "fixture": false,
    "ignore_submodules": null
  },
  ...
]
```
As a result, every time `remote` needs to be accessed, there is an extra step where `git remote get-url origin` is run. We can avoid that by storing the complete URL of each repo in `state.json`. For example
```yaml
[
  {
    "name": "GEOSgcm",
    "local": ".",
    "remote": "https://github.com/GEOS-ESM/GEOSgcm.git",       # <--- changed
    "version": [
      "v11.5.2",
      "t",
      true
    ],
    "sparse": null,
    "develop": "main",
    "recurse_submodules": null,
    "fixture": true,
    "ignore_submodules": null
  },
  {
    "name": "env",
    "local": "@env",
    "remote": "https://github.com/GEOS-ESM/ESMA_env.git",      # <--- changed
    "version": [
      "v4.25.1",
      "t",
      true
    ],
    "sparse": null,
    "develop": "main",
    "recurse_submodules": null,
    "fixture": false,
    "ignore_submodules": null
  },
  ...
]
```
