### ISSUE TITLE
Add blobless option in components.yaml

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#347]
As found by @bena-nasa and @weiyuan-jiang, the NCAR topo repo is *big*, around 2.7G all in the `.git/` directory. But if you clone as blobless, it's only 1.7M.

So, it would be nice to "force" mepo to clone certain repos (like MAPL or topo) as blobless even if a user hasn't asked for a blobless clone a la:

```yaml
MAPL:
  local: ./src/Shared/@MAPL
  remote: ../MAPL.git
  tag: v2.53.1
  develop: develop
  blobless: true
```
