### ISSUE TITLE
Fixture extension

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/mepo#349]
Add ability to extend a (base) fixture. This would enable creation of fixtures with simplified registry. For example, the registry below extends a particular version of the base fixture GEOSgcm with a version of MAM. At the same time, it has the flexibility to override the version of a component from the base fixture.
```yaml
GEOSmam:
  fixture: true
  develop: main
  extends:
    GEOSgcm:
      tag: v11.7.0
      remote: ../GEOSgcm.git

extensions:
  MAM:
    local: ./src/Components/@GEOSgcm_GridComp/.../@GEOSchem_GridComp/@MAM
    remote: ../MAM.git
    tag: v1.0.0
    develop: develop

overrides:
  GEOSgcm_GridComp:
    local: ./src/Components/@GEOSgcm_GridComp
    remote: ../GEOSgcm_GridComp.git
    tag: v2.7.2
    sparse: ./config/GEOSgcm_GridComp.sparse
    develop: develop
```
For the first step, restrict to single level extension from a single base fixture.
